### ISSUE TITLE
A request

### ISSUE THREAD

**Issue by FourteenObsidians** [ycpedef/checker#1]
Could you make a make-data schema?(Supporting gradient data)

**Comment by cauphenuny** [comment]
What do you mean? What kind of schema?

**Comment by FourteenObsidians** [comment]
造数据，有梯度

**Comment by FourteenObsidians** [comment]
I am a Chinese!

**Comment by cauphenuny** [comment]
You can make gradient data by a better generator, it is none of checker's business

**Comment by FourteenObsidians** [comment]
But how to do that?
